import Head from "next/head";
import { useState } from "react";

import  Cadrasto  from "../../components/Cadrasto";
import  Login from "../../components/Login";
import { GlobalStyle } from "../styles/GlobalStyle";

import * as Style from "../styles/style";

export default function Home() {

  const[cadrastar,setCadrastar] = useState(false)

  
  return (
    
    <>
      <Head>
        <title>formulario</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Style.Main>
        <GlobalStyle/>
        <section>
          <div className="conteinerImg">
            <img src="/img.svg" alt="" />
          </div>
          <div className="conteinerForm">
           {!cadrastar && <Login isCadrastar={setCadrastar}/>} 
           {cadrastar && <Cadrasto isCadrastar={setCadrastar}/>}
          </div>
        </section>
      </Style.Main>
    </>
  );
}
